### ISSUE TITLE
Add satellite name and their messages.

### ISSUE THREAD

**Issue by Harsh005385** [semuconsulting/pyrtcm#15]
**Is your feature request related to a problem? Please describe.**

I can't parsing the data of IRNSS MSM data so please add it in library.

**Describe the solution you'd like**

I add IRNSS in below modules.
1.) rtcmtables.py
2.) rtcmtypes.py
3.) rtcmhelpers.py
4.) rtcmtypes_get.py

**Describe alternatives you've considered**

I add these properly but still there is an error.

**Would you be willing to assist with testing?**

I want to assist regarding RTCM 10403.3 and message types are IRNSS -> MSM(1131-1137).

**Additional context**

Tell me the solution. And I got error 
TypeError: 'NpneType' object is not subscriptable.

**Comment by semuadmin** [comment]
Hi @Harsh005385 ,

You haven't actually provided any code samples so I can't possibly "tell you the solution" or debug the Nonetype error you're getting. 

I you have fully tested code and would like to submit a Pull Request, please use the template provided. 

Otherwise, please provide further information and code samples to help me understand your issues.
