### ISSUE TITLE
Message Type 1230 Parsing

### ISSUE THREAD

**Issue by jcmb** [semuconsulting/pyrtcm#19]
**Describe the bug**

In rtcmtypes_get.py there is a TODO for message 1230

        # TODO verify that each iteration of this group only ever contains
        # one of either DF423, DF424, DF425 or FD426?

This is not the case. 

Using a Trimble SPS855 or R750 data stream as an example, DF422 is 15, which indicate that aDF423-DF426 is present. 

message print.
<RTCM(1230, DF002=1230, DF003=4, DF421=0, DF001_3=0, DF422=15, DF423_01=19.06, DF423_02=19.06, DF423_03=19.06, DF423_04=19.06)>

{'DF001_3': 'Reserved',
 'DF002': 'Message Number',
 'DF003': 'Reference Station ID',
 'DF421': 'GLONASS Code-Phase bias indicator',
 'DF422': 'GLONASS FDMA signals mask',
 'group': ('_NBias', {'DF423': 'GLONASS L1 C/A Code-Phase Bias'})}

You will notice that DF423 has 4 repeats, DF423_01 to DF423_04. DF423 is not a repeating value, and DF422 is not a number of items indicator. It is a bit mask of the fields following.

If you remove # from the definition of NBIAS so DF DF424-DF426 are defined I think it does not parse 1230 correctly. 

        "group": (
            NBIAS,
            {
                "DF423": "GLONASS L1 C/A Code-Phase Bias",
                "DF424": "GLONASS L1 P Code-Phase Bias",
                "DF425": "GLONASS L2 C/A Code-Phase Bias",
                "DF426": "GLONASS L2 P Code-Phase Bias",
            },

message print.
<RTCM(1230, DF002=1230, DF003=11, DF421=0, DF001_3=0, DF422=15, DF423_01=19.06, DF424_01=19.06, DF425_01=19.06, DF426_01=19.06, DF423_02=0, DF424_02=0, DF425_02=0, DF426_02=0, DF423_03=0, DF424_03=0, DF425_03=0, DF426_03=0, DF423_04=0, DF424_04=0, DF425_04=0, DF426_04=0)>

You see the same issue with _01-_04, but it is does have DF423-DF426.

{'DF001_3': 'Reserved',
 'DF002': 'Message Number',
 'DF003': 'Reference Station ID',
 'DF421': 'GLONASS Code-Phase bias indicator',
 'DF422': 'GLONASS FDMA signals mask',
 'group': ('_NBias',
           {'DF423': 'GLONASS L1 C/A Code-Phase Bias',
            'DF424': 'GLONASS L1 P Code-Phase Bias',
            'DF425': 'GLONASS L2 C/A Code-Phase Bias',
            'DF426': 'GLONASS L2 P Code-Phase Bias'})}

**To Reproduce**

SPS855.COM port 28003 has a RTCM V3.x stream showing this behaviour. The dump above is from that stream. 

I do not have access to a unit that only outputs a subset of the biases.

- Trimble Precise GNSS. 
- Firmware 5.60
- RTCM V3

**Comment by semuadmin** [comment]
Hi @jcmb

Apologies but I'm not clear what you're saying the issue is?

I acknowledge the TODO comment needs removing, but are you saying the current 1230 payload definition is incorrect? If so, can you post what you believe to be the correct complete definition?

The number of repeats in the repeating group is defined by the number of bits set in the DF422 value (= NBIAS). A value of 15 = 0b1111 = 4 bits set, so NBIAS = 4). But the RTCM specification is unclear about how you tell if the repeating group contains DF423, DF424, DF425 or DF426 values.


--
semuadmin
SEMU Consulting
https://github.com/semuconsulting
________________________________
From: jcmb ***@***.***>
Sent: Sunday, March 5, 2023 5:33:40 AM
To: semuconsulting/pyrtcm ***@***.***>
Cc: semuadmin ***@***.***>; Assign ***@***.***>
Subject: [semuconsulting/pyrtcm] Message Type 1230 Parsing (Issue #19)


Describe the bug

In rtcmtypes_get.py there is a TODO for message 1230

    # TODO verify that each iteration of this group only ever contains
    # one of either DF423, DF424, DF425 or FD426?


This is not the case.

Using a Trimble SPS855 or R750 data stream as an example, DF422 is 15, which indicate that aDF423-DF426 is present.

message print.
<RTCM(1230, DF002=1230, DF003=4, DF421=0, DF001_3=0, DF422=15, DF423_01=19.06, DF423_02=19.06, DF423_03=19.06, DF423_04=19.06)>

{'DF001_3': 'Reserved',
'DF002': 'Message Number',
'DF003': 'Reference Station ID',
'DF421': 'GLONASS Code-Phase bias indicator',
'DF422': 'GLONASS FDMA signals mask',
'group': ('_NBias', {'DF423': 'GLONASS L1 C/A Code-Phase Bias'})}

You will notice that DF423 has 4 repeats, DF423_01 to DF423_04. DF423 is not a repeating value, and DF422 is not a number of items indicator. It is a bit mask of the fields following.

If you remove # from the definition of NBIAS so DF DF424-DF426 are defined I think it does not parse 1230 correctly.

    "group": (
        NBIAS,
        {
            "DF423": "GLONASS L1 C/A Code-Phase Bias",
            "DF424": "GLONASS L1 P Code-Phase Bias",
            "DF425": "GLONASS L2 C/A Code-Phase Bias",
            "DF426": "GLONASS L2 P Code-Phase Bias",
        },


message print.
<RTCM(1230, DF002=1230, DF003=11, DF421=0, DF001_3=0, DF422=15, DF423_01=19.06, DF424_01=19.06, DF425_01=19.06, DF426_01=19.06, DF423_02=0, DF424_02=0, DF425_02=0, DF426_02=0, DF423_03=0, DF424_03=0, DF425_03=0, DF426_03=0, DF423_04=0, DF424_04=0, DF425_04=0, DF426_04=0)>

You see the same issue with _01-_04, but it is does have DF423-DF426.

{'DF001_3': 'Reserved',
'DF002': 'Message Number',
'DF003': 'Reference Station ID',
'DF421': 'GLONASS Code-Phase bias indicator',
'DF422': 'GLONASS FDMA signals mask',
'group': ('_NBias',
{'DF423': 'GLONASS L1 C/A Code-Phase Bias',
'DF424': 'GLONASS L1 P Code-Phase Bias',
'DF425': 'GLONASS L2 C/A Code-Phase Bias',
'DF426': 'GLONASS L2 P Code-Phase Bias'})}

To Reproduce

SPS855.COM port 28003 has a RTCM V3.x stream showing this behaviour. The dump above is from that stream.

I do not have access to a unit that only outputs a subset of the biases.

  *   Trimble Precise GNSS.
  *   Firmware 5.60
  *   RTCM V3

**Comment by semuadmin** [comment]
Hi [@jcmb](https://github.com/jcmb)

The number of repeats in the 1230 repeating group is defined by the number of bits set in the DF422 value (= NBIAS). A value of 15 = 0b1111 = 4 bits set). I believe the first bit (MSB), and therefore the first value in the repeating group refers to the L1 C/A value (DF423), the second refers to the L1 P value (DF424), the third refers to the L2 C/A value (DF425) and the fourth to the L2 P value (DF426).

So the overall structure of the 1230 payload is correct but I need to refine the data field labels - something like this...

```    
"1230": {
        "DF002": "Message Number",
        "DF003": "Reference Station ID",
        "DF421": "GLONASS Code-Phase bias indicator",
        "DF001_3": "Reserved",
        "DF422": "GLONASS FDMA signals mask",
        "groupL1CA": (
            NL1CA,  # = 1 if bit 1 (MSB) in DF422 is set, otherwise 0
            {
                "DF423": "GLONASS L1 C/A Code-Phase Bias",
            },
        ),
        "groupL1P": (
            NL1P,  # = 1 if bit 2 in DF422 is set, otherwise 0
            {
                "DF424": "GLONASS L1 P Code-Phase Bias",
            },
        ),
        "groupL2CA": (
            NL2CA,  # = 1 if bit 3 in DF422 is set, otherwise 0
            {
                "DF425": "GLONASS L2 C/A Code-Phase Bias",
            },
        ),
        "groupL2P": (
            NL2P,  # = 1 if bit 4 (LSB) in DF422 is set, otherwise 0
            {
                "DF426": "GLONASS L2 P Code-Phase Bias",
            },
        ),
    },
```


Is this consistent with your understanding?

**Comment by jcmb** [comment]
That is perfect.
